name: Test, build and publish
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  DOCKER_HUB_REPO: jenswbe/dead-link-checker
  DOCKER_HUB_USER: jenswbebot

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Derive docker tags
        id: vars
        shell: python
        run: |
          import os, re, sys
          tag = os.environ['GITHUB_REF'].split('/').pop()
          print(f"Tag: {tag}")
          tags = []
          semverRegex = r"^v\d+\.\d+\.\d+$"
          if tag == 'main':
            tags = ['latest']
          elif re.match(semverRegex, tag):
            tag_parts = tag.split(".")
            tags = ['stable', tag, tag_parts[0], f"{tag_parts[0]}.{tag_parts[1]}"]
          else:
            tags = [f'test-branch-{tag}']
          tags_list = ",".join(tags)
          print(f"Tags: {tags_list}")
          with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
            output.write(f"tags={tags_list}{os.linesep}")

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version: "1.26"

      - name: Pull common linter configs
        run: wget -O .golangci.yml https://raw.githubusercontent.com/JenswBE/setup/main/programming_configs/golang/.golangci.yml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Ensure all fixes are applied
        run: |
          go fix ./...
          git diff --exit-code

      - name: Start E2E services
        working-directory: e2e
        run: |
          docker compose up -d
          sleep 5s

      - name: Run E2E tests
        working-directory: e2e
        run: go test --tags e2e ./...

      - name: Setup Ko
        if: github.event_name == 'push'
        uses: ko-build/setup-ko@v0.9
        with:
          version: v0.18.1
        env:
          KO_DOCKER_REPO: docker.io/${{ env.DOCKER_HUB_REPO }}

      - name: Build with Ko
        if: github.event_name == 'push'
        env:
          oci_registry: docker.io
          oci_auth_user: ${{ env.DOCKER_HUB_USER }}
          oci_auth_token: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          # Ensure git repo is clean
          git reset --hard HEAD

          # Login to OCI registry
          echo "${oci_auth_token:?}" | ko login "${oci_registry:?}" --username "${oci_auth_user:?}" --password-stdin

          # Build image
          ko build ./cmd --platform=all --tags ${{ steps.vars.outputs.tags }} --bare

      - name: Update repo description
        if: github.event_name == 'push'
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.DOCKER_HUB_REPO }}
